version: '3'
services:
  database:
    container_name: container-pg
    image: postgis/postgis:14-3.4-alpine
    # image: postgres:14.12
    hostname: localhost
    restart: always
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simki
    volumes:
      - ./database/db-data/:/var/lib/postgresql/data/
